### ISSUE TITLE
Training on GPU

### ISSUE THREAD

**Issue by Abdallah-Khx** [EQTPartners/PTEC#1]
How do I make my data run on my gpu not cpu there is a bash command but that is only for linux and it doesn't work for windows is there a specific command for windows to make the training on gpu not cpu

**Comment by valentinbuc** [comment]
Hey @AlphaKh,

I would recommend installing a Windows Subsystem for Linux (WSL). Once installed, you can open the WSL terminal and run the bash commands as provided in the readme. 

Alternatively, you can also open the .sh files and run the python commands in your windows command prompt. That will only be a few more commands to run, but will have the same effect.

**Comment by valentinbuc** [comment]
I am glad to hear that, would be happy to hear about the results of your project!

For calculating the performance, I used the `classification_report` from `sklearn.metrics`. I can see how I implemented it here https://github.com/EQTPartners/PTEC/blob/main/sectors/utils/evaluation.py

The computational costs were a bit more complex to calculate. I used `torch.profiler.profile`, you can see how I implemented it here: https://github.com/EQTPartners/PTEC/blob/main/sectors/experiments/test_flops.py 
As the profiler itself uses a lot of memory, this was only done for a small set of samples, and then I extrapolated the FLOPs used on these samples to the complete prompt-tuning and inference process.

**Comment by AlphaKh** [comment]
One last thing regarding the results, what are we supposed to compare exactly because as I said we didn't do any experiments on Huggingllama because it's too big with 7b parameters. So are we supposed to compare the methods done on the experiments for bigscience?

**Comment by valentinbuc** [comment]
If you are limited in computing resources, it may indeed be ideal to work with the bigscience/bloom models!

If you don't aim for an exact reproduction but also want to extend the study a bit, it should also be interesting to try out some of the newer and smaller models like gemma 2B. That would probably require some adjustments to the codebase however!

**Comment by AlphaKh** [comment]
Thank you so much for your recommendations, would you mind if you record yourself for 30s and in these 30s If you don't mind complementing our work integrity and ethics some things along the line "They contacted me about the models testing and training error'' This will be used in out presentation to help us stand out and we appreciate all the effort you helped us in.

**Comment by valentinbuc** [comment]
Your team definitely put great effort into this project, and I can endorse that you contacted me to clarify questions. I would be curious to read your report and have a look at your findings!
